### ISSUE TITLE
Add docs for installing on PKS

### ISSUE THREAD

**Issue by trisberg** [projectriff/projectriff.io#54] opened 2018-10-16 19:13 UTC
See: https://content.pivotal.io/blog/why-serverless-matters-to-your-enterprise-a-look-at-common-use-cases-plus-a-quick-tutorial-with-riff-and-kubernetes

**Comment by glyn** [comment] 2018-11-26 15:35
What, if anything, remains to be done now that https://github.com/pivotal-cf/docs-pfs/pull/11 is merged? /cc @georgeharley

**Comment by jldec** [comment] 2018-11-28 08:35
not required for riff v0.2.0 milestone.

**Comment by glyn** [comment] 2018-11-28 09:02
The title of this issue is misleading if the issue is actually about linking to the blog in the first comment.

**Comment by scothis** [comment] 2019-10-16 14:54
PKS is not a supported environment for riff

**Closed as completed by scothis** 2019-10-16 14:54 UTC
